/* Exec Comms — Session Data */

const PHASES = [
  { id:1, title:"Strategic Framing", weeks:"1–3", q:"Why did this matter to the business — and can I say it without mentioning design?" },
  { id:2, title:"Leadership Narrative", weeks:"4–6", q:"How did I lead — not what did I design?" },
  { id:3, title:"Executive Presence + Vision", weeks:"7–8", q:"How do I sound when I speak to C-level — and can I communicate a broader vision?" },
  { id:4, title:"Integration & Stress Testing", weeks:"9–10", q:"Can I do this consistently — under pressure, in real situations?" },
];

const S = [
  {w:1,d:"Mon",p:1,t:"Read: Pyramid Principle Ch.1",tm:"30–45 min",tp:"reading",
   b:"Read Chapter 1: \"Why a Pyramid Structure?\" (~15–20 pages). The chapter explains why the human mind groups information into pyramids and why you should lead with the main idea, then support it.\n\n**Do this:**\n1. Read the chapter. (20–25 min)\n2. Open your rewritten FTU case study opening. Does your opening follow the pyramid structure? Or does it build up to the point? (10 min)\n3. Write one sentence summarizing what you'd change. (5 min)",
   up:"Your assessment + the one sentence.",rs:"The Pyramid Principle, Ch.1"},
  {w:1,d:"Tue",p:1,t:"Write: Three Business Openings for FTU",tm:"30–35 min",tp:"writing",
   b:"Write three alternative FTU openings — each leading with a different business angle:\n1. Version A: Lead with the revenue risk (LTV, diversification)\n2. Version B: Lead with the competitive/market pressure\n3. Version C: Lead with the organizational challenge\n\n**Rules:**\n- No design terminology in the first four sentences\n- Each version must open with the opportunity or ambition *before* naming the problem",
   up:"All three versions.",rs:"—"},
  {w:1,d:"Wed",p:1,t:"Read: Stripe 2025 Annual Letter",tm:"30–45 min",tp:"reading",
   b:"Go to stripe.com/annual-updates/2025. Read the first half.\n\n**While reading, note:**\n1. How do they describe a product decision?\n2. What language do they use for growth?\n3. How do they frame challenges?\n\n**Then:** Pick one SumUp challenge and rewrite it using Stripe's patterns. Max 5 sentences.",
   up:"Your three observations + the rewritten paragraph.",rs:"Stripe 2025 Letter"},
  {w:1,d:"Thu",p:1,t:"Write: Verbal Script FTU Beat 1",tm:"25–35 min",tp:"writing",
   b:"Write the full verbal script for the first 2 minutes of your FTU presentation.\n\n**Specs:**\n- 200–250 words\n- No screen mentions, no flow descriptions, no UI patterns\n- Only: business context, strategic framing, why this mattered to SumUp\n- Must open with a positive/opportunity statement before naming the problem",
   up:"The script.",rs:"—"},
  {w:1,d:"Fri",p:1,t:"Practice: 2-Min Business Setup",tm:"45–60 min",tp:"practice",
   b:"Present your FTU Beat 1 script out loud.\n\n**Solo version:**\n1. Set up your phone camera (2 min)\n2. Present 2–3 times, pick the best take (15 min)\n3. Watch without sound — check body language (5 min)\n4. Watch with sound — check language (5 min)\n5. Score: Business context? Jargon-free? Positive-first? Confident? Would a CFO lean in?",
   up:"Self-score + notes. Keep the recording.",rs:"—"},
  {w:2,d:"Mon",p:1,t:"Write: The 'So What' Chain",tm:"35 min",tp:"writing",
   b:"Map the \"So What\" chain for 5 features (3 FTU, 2 P&S). Each as a chain of 2–4 arrows connecting to a company KPI.\n\n**Example:**\n\"Intent-gathering in onboarding\" → \"Personalized guidance\" → \"+9.3% multi-product adoption\" → \"Revenue diversification target\"",
   up:"Your five chains.",rs:"—"},
  {w:2,d:"Tue",p:1,t:"Write: Results Narrative (Two Versions)",tm:"40 min",tp:"writing",
   b:"Write FTU results as a 4-sentence narrative paragraph. No bullets.\n\n**Two versions:**\n- A: Lead with the problem, then the result (your instinct)\n- B: Lead with the result and what it enabled (Director pattern)\n\n**Then** do the same for P&S, also addressing the measurability gap.",
   up:"Both versions of both narratives (4 paragraphs total).",rs:"—"},
  {w:2,d:"Wed",p:1,t:"Read: Pyramid Principle Ch.2",tm:"30–40 min",tp:"reading",
   b:"Read Chapter 2: \"The Substructures Within the Pyramid\" — vertical relationships, horizontal relationships, and SCQA.\n\n**Do this:**\n1. Read the chapter. (20–25 min)\n2. Take your strongest \"So What\" chain. Rewrite it as SCQA: Situation → Complication → Question → Answer. Max 4 sentences.",
   up:"Your SCQA paragraph.",rs:"The Pyramid Principle, Ch.2"},
  {w:2,d:"Thu",p:1,t:"Write: 'What I'd Do Differently'",tm:"40 min",tp:"writing",
   b:"Write a \"What I'd do differently\" section for FTU and P&S.\n\n**Rules:**\n- 100–150 words each\n- Frame as what you'd *optimize*, not what went wrong\n- \"Next time I'd establish shared measurement from day one\" — NOT \"We didn't have proper measurement\"",
   up:"Both sections.",rs:"—"},
  {w:2,d:"Fri",p:1,t:"Practice: 90-Second Results Pitch",tm:"45–60 min",tp:"practice",
   b:"Present FTU results in exactly 90 seconds.\n\n**Structure:**\n1. Biggest business number (10 sec)\n2. What it means for the company (40 sec)\n3. One thing you'd do differently (20 sec)\n4. What this says about you as a leader (20 sec)\n\nTarget: 70%+ positive-first sentences.",
   up:"Self-score + positive-framing count.",rs:"—"},
  {w:3,d:"Mon",p:1,t:"Read: Stripe 2024 Annual Letter",tm:"30–40 min",tp:"reading",
   b:"Read the full letter at stripe.com/annual-updates/2024.\n\n**Compare to 2025:**\n1. How did their framing change year-over-year?\n2. Pick one challenge paragraph. Rewrite a SumUp challenge using their sentence structure.",
   up:"Comparison notes + SumUp paragraph.",rs:"Stripe 2024 Letter"},
  {w:3,d:"Tue",p:1,t:"Read: Positive Communication for Leaders",tm:"35–40 min",tp:"reading",
   b:"Read the opening chapters. Focus on: how positive framing differs from sugar-coating.\n\n**Do this:**\n1. Read for 25 min.\n2. Write: 3 techniques most relevant to your negative-first habit. (10 min)\n3. Pick one. Find one FTU sentence to apply it to. Write before/after. (5 min)",
   up:"Your 3 techniques + the before/after pair.",rs:"Positive Communication for Leaders"},
  {w:3,d:"Wed",p:1,t:"Write: Positive-First Rewrite Exercise",tm:"35 min",tp:"writing",
   b:"Find 5 sentences across your case studies that open with a problem. Rewrite each to lead with the positive.\n\n**Example:**\n- Before: \"20% never completed their first transaction, threatening activation.\"\n- After: \"SumUp was building a multi-product ecosystem — first-transaction completion was the gateway.\"",
   up:"The 5 before/after pairs.",rs:"Positive Communication for Leaders"},
  {w:3,d:"Thu",p:1,t:"Write: Verbal Script P&S Beat 1",tm:"40 min",tp:"writing",
   b:"Write the first 2 minutes of your P&S presentation.\n\nSame specs as Week 1 Thu: 200–250 words, no UI mentions, opens with opportunity, business language only.\n\n**Then:** Compare to your FTU script. Which structure is stronger?",
   up:"The P&S script + comparison notes.",rs:"—"},
  {w:3,d:"Fri",p:1,t:"Practice: 2-Min P&S Business Setup",tm:"45–60 min",tp:"practice",
   b:"Same format as Week 1 Fri, but for P&S.\n\nRecord, watch back, score on the same grid. Compare scores to Week 1 Fri.",
   up:"Self-score + comparison to Week 1.",rs:"—"},
  {w:4,d:"Mon",p:2,t:"Analysis: The Delegation Audit",tm:"35–40 min",tp:"analysis",
   b:"Label every action sentence in your FTU case:\n- **D** = I directed (set the frame, made the call)\n- **E** = I executed (hands-on design, research)\n- **G** = I grew someone (coached, delegated with intent)\n\nTarget: 60%+ D+G. Note 5 sentences to reframe.",
   up:"Labeled audit + 5 reframe candidates.",rs:"—"},
  {w:4,d:"Tue",p:2,t:"Write: Three Leadership Micro-Stories",tm:"30 min",tp:"writing",
   b:"Three micro-stories (3–4 sentences each):\n1. A difficult prioritization call\n2. Something you deliberately delegated\n3. A team member you grew\n\n**Rules:** Name by role, state what you did, state the result. First sentence leads with what you enabled.",
   up:"All three micro-stories.",rs:"—"},
  {w:4,d:"Wed",p:2,t:"Watch/Listen: Senior Design Leaders",tm:"30–45 min",tp:"reading",
   b:"Pick ONE: Figma Config 2024 leadership talk / Design Matters episode / Lenny's Podcast with a Director+ guest.\n\n**Note:**\n1. How they describe their role\n2. \"I\" vs. \"we\" vs. \"my team\" ratio\n3. Vision-led or problem-led?",
   up:"3 observations + 1 phrase to adopt.",rs:"Figma Config / Design Matters / Lenny's"},
  {w:4,d:"Thu",p:2,t:"Rewrite: Strengthening Beat 2",tm:"45–55 min",tp:"writing",
   b:"Review 'How I Led' in FTU and P&S. Check:\n1. Team structure with *rationale*?\n2. Delegation specific?\n3. Growth moment?\n4. Stakeholder alignment as *your* contribution?\n\nRewrite sections that fail.",
   up:"Both revised 'How I Led' sections.",rs:"—"},
  {w:4,d:"Fri",p:2,t:"Practice: FTU Story (No Design)",tm:"45–60 min",tp:"practice",
   b:"Present FTU in 5 minutes — no screens, no UI, no design artifacts. Only: business problem, your team, your decisions, results.\n\nCount: (a) team/people mentions, (b) your decisions, (c) UI mentions. Target: 70%+ on (a)+(b).",
   up:"Self-count + transcript or notes.",rs:"—"},
  {w:5,d:"Mon",p:2,t:"Write: Four-Beat Skeleton (Exp. Design)",tm:"40 min",tp:"writing",
   b:"Map Experience Design Team using four beats:\n1. Business Context: Why did SumUp need this team?\n2. How I Led: Hiring, philosophy, breaking silos\n3. Design Approach: Systems, guidelines, community\n4. Outcomes: eNPS 100, 90+ community, principle adoption",
   up:"Your four paragraphs.",rs:"—"},
  {w:5,d:"Tue",p:2,t:"Write: Org Impact Without Metrics",tm:"30 min",tp:"writing",
   b:"Three questions (3–5 sentences each):\n1. How do you measure team success without revenue?\n2. What changed at SumUp because this team existed?\n3. Hardest thing about building from zero?\n\nEach answer's first sentence must be positive.",
   up:"All three answers.",rs:"—"},
  {w:5,d:"Wed",p:2,t:"Write: Influence-Without-Authority",tm:"30 min",tp:"writing",
   b:"Two moments where you influenced without direct authority. Each as 3 sentences: Context → What you did → What happened.\n\nThese should sound like Director moves (coalition-building, shared narrative) not Lead moves.",
   up:"Both influence stories.",rs:"—"},
  {w:5,d:"Thu",p:2,t:"Write: Full Exp. Design Narrative",tm:"45–60 min",tp:"writing",
   b:"Expand your skeleton to 600–800 words.\n\n**Focus:**\n- Why growth *required* a different approach to design coherence\n- Specific hiring criteria, culture decisions, breaking silos\n- Frame eNPS, community, principles as *organizational assets*",
   up:"The full draft.",rs:"—"},
  {w:5,d:"Fri",p:2,t:"Practice: Present the Non-Metric Story",tm:"45–60 min",tp:"practice",
   b:"Present Exp. Design Team in 5 minutes. No revenue numbers to fall back on.\n\nAsk: \"Is this a Director telling a team story, or someone showing their org chart?\"\n\nDid you open with the vision before explaining why it didn't exist yet?",
   up:"Self-review + confidence rating (1–10).",rs:"—"},
  {w:6,d:"Mon",p:2,t:"Analysis: Full Language Audit",tm:"35–45 min",tp:"analysis",
   b:"Label every sentence across all case studies + portfolio intro:\n- **L** = Lead language (craft-focused)\n- **D** = Director language (business, team, org)\n- **N** = Negative-first\n\nHit list: 10 sentences that most need reframing. Prioritize L+N.",
   up:"Ratio count + 10-sentence hit list.",rs:"—"},
  {w:6,d:"Tue",p:2,t:"Write: Three Elevator Pitches",tm:"30 min",tp:"writing",
   b:"Three 60-second intros (~150 words each):\n1. VP of Design at a fintech\n2. CEO/CPO skeptical about design leadership\n3. Networking event\n\nEach: title, one business result, one team achievement, what you seek. Opens with a forward-looking positive.",
   up:"All three versions.",rs:"—"},
  {w:6,d:"Wed",p:2,t:"Read: Wise FY2025 Investor Results",tm:"30–40 min",tp:"reading",
   b:"Read the FY2025 summary at wise.com/owners/results-reports-presentations.\n\nHow do they structure for investors? Numbers or narrative first? How do they frame growth vs. challenges?\n\nWrite your FTU results in investor language. Max 4 sentences.",
   up:"Observations + investor-language paragraph.",rs:"Wise FY2025 Results"},
  {w:6,d:"Thu",p:2,t:"Rewrite: 10 Worst Sentences",tm:"50 min",tp:"writing",
   b:"Rewrite all 10 sentences from Monday's hit list. Transform from Lead+Negative to Director+Positive.\n\n**Rules:**\n- Lead with what you built/achieved/enabled\n- Replace craft language with business/team/org language\n- Would a non-designer understand this?",
   up:"The 10 before/after pairs.",rs:"Positive Communication for Leaders"},
  {w:6,d:"Fri",p:2,t:"Practice: 3-Min Portfolio Walk",tm:"45–60 min",tp:"practice",
   b:"Walk through your portfolio in 3 minutes. Record.\n\nTranscribe first 5 sentences. Do they lead with accomplishment or problems?\n\nDelete every sentence a Senior Designer could say. What's left is your Director signal.",
   up:"Transcript analysis + framing audit.",rs:"—"},
  {w:7,d:"Mon",p:3,t:"Read: Pyramid Principle Ch.3",tm:"30–40 min",tp:"reading",
   b:"Chapter 3: \"How to Build a Pyramid Structure\" — top-down vs. bottom-up approach.\n\n1. Read the chapter. (20–25 min)\n2. What is the ONE main message of your FTU case? Write it as one sentence. List 3–4 supporting arguments. (10–15 min)",
   up:"Pyramid structure (message + supports).",rs:"The Pyramid Principle, Ch.3"},
  {w:7,d:"Tue",p:3,t:"Write: Audience-First Framework",tm:"30–35 min",tp:"writing",
   b:"Describe FTU for four audiences (3 sentences each):\n1. Design team (craft, learnings)\n2. PM/EM peers (trade-offs, timelines)\n3. VP/CPO (business case, results)\n4. CEO/board (one number, strategic implication)\n\nAudiences 3+4: first sentence must be positive impact.",
   up:"All four summaries.",rs:"—"},
  {w:7,d:"Wed",p:3,t:"Read: The Power of Framing",tm:"35 min",tp:"reading",
   b:"Opening chapters of *The Power of Framing*. How leaders use framing to shape interpretation.\n\n1. Read for 25 min.\n2. For each audience: what *frame* should they walk away with? One sentence each.",
   up:"Framing notes + 4 audience frames.",rs:"The Power of Framing"},
  {w:7,d:"Thu",p:3,t:"Write: The Upward Update",tm:"25–30 min",tp:"writing",
   b:"Two fictional status updates mid-FTU project:\n1. VP weekly (max 5 sentences): decision/risk → number → ask\n2. C-level Slack (max 3 sentences): momentum → blocker → ask\n\nNo design jargon. Only decisions, risks, results, asks.",
   up:"Both updates.",rs:"—"},
  {w:7,d:"Fri",p:3,t:"Read: Pyramid Principle Ch.4 or 5",tm:"30–35 min",tp:"reading",
   b:"Ch.4 (SCQA for openings) or Ch.5 (logical ordering). Pick what's more relevant.\n\n1. Read. (20–25 min)\n2. Take your longest case study paragraph. Rewrite using BLUF — conclusion first. (10 min)",
   up:"Your BLUF rewrite.",rs:"The Pyramid Principle, Ch.4/5"},
  {w:8,d:"Mon",p:3,t:"Write: Q&A Prep (FTU Only)",tm:"35 min",tp:"writing",
   b:"Director-level answers (3–4 sentences) to:\n1. \"Walk me through your decision-making.\"\n2. \"What did you personally do vs. delegate?\"\n3. \"How does this connect to company strategy?\"\n4. \"Biggest mistake and learning?\"\n5. \"Someone you grew through this?\"\n\nPlus 2 hard FTU-specific questions.",
   up:"The 7 Q&A pairs.",rs:"—"},
  {w:8,d:"Tue",p:3,t:"Write: Q&A Prep (P&S + Exp. Design)",tm:"50–60 min",tp:"writing",
   b:"Same format for both remaining case studies. 5 standard + 2 hard each = 14 Q&A pairs total.",
   up:"The 14 Q&A pairs.",rs:"—"},
  {w:8,d:"Wed",p:3,t:"Write: Cross-Case Meta-Narrative",tm:"30–40 min",tp:"writing",
   b:"200-word meta-narrative tying all three cases together.\n\nTest: \"I build frameworks that scale\" / \"I connect brand, product, and growth\" / \"I identify org-level problems and design through them\"\n\nLead with what you create and enable.",
   up:"Meta-narrative + chosen through-line.",rs:"—"},
  {w:8,d:"Thu",p:3,t:"Write: Five Hard Question Answers",tm:"50 min",tp:"writing",
   b:"Five uncomfortable questions:\n1. \"How do I know that was you, not your team?\"\n2. \"You've been at SumUp long — can you adapt?\"\n3. \"Your portfolio shows craft. We need someone who won't touch Figma.\"\n4. \"A project where your leadership failed.\"\n5. \"The Raisin process. What happened?\"\n\nEach opens with confidence. Vulnerability comes second.",
   up:"All five answers.",rs:"Thanks for the Feedback (optional)"},
  {w:8,d:"Fri",p:3,t:"Practice: Mock Q&A (All Cases)",tm:"45–60 min",tp:"practice",
   b:"Present one case in 5 min, then Q&A under pressure. 90 seconds per answer.\n\nFocus: under pressure, do you default to (a) design details, (b) negative framing, or (c) Director level?",
   up:"Self-assessment — which questions made you drop?",rs:"—"},
  {w:9,d:"Mon",p:4,t:"Practice: FTU Full Narrative",tm:"45–60 min",tp:"practice",
   b:"Complete FTU verbal narrative aloud. Target 7–10 minutes.\n\nCheck beat allocation: ~20% Context / 25% How I Led / 30% Approach / 25% Outcomes.",
   up:"Timing + balance assessment.",rs:"—"},
  {w:9,d:"Tue",p:4,t:"Practice: P&S + Exp. Design Full",tm:"45–60 min",tp:"practice",
   b:"Same for both remaining cases. Target 5–7 minutes each.",
   up:"Timing + balance for both.",rs:"—"},
  {w:9,d:"Wed",p:4,t:"Rewrite: Portfolio + LinkedIn + a16z",tm:"30–45 min",tp:"writing",
   b:"Final pass on all public text:\n- Portfolio intro: business outcomes first?\n- LinkedIn: Director-level?\n- a16z: matches improved cases?\n\nFirst sentence of every public text must state what you built.",
   up:"All revised text.",rs:"—"},
  {w:9,d:"Thu",p:4,t:"Write: Cold Outreach (3 Companies)",tm:"45 min",tp:"writing",
   b:"Outreach to three real companies:\n1. Growth-stage fintech\n2. Mature product company\n3. Company where design is undervalued\n\nLead with business impact, mention team-building, connect to their challenges. No portfolio link first.",
   up:"All three messages.",rs:"—"},
  {w:9,d:"Fri",p:4,t:"Practice: Full Mock Interview",tm:"45–60 min",tp:"practice",
   b:"5-min intro → 10-min case → 15-min Q&A. Record 30 minutes.\n\nCompare opening 2 minutes to Week 1. Score: Director or Lead? Positive or negative default?",
   up:"Self-review + comparison to Week 1.",rs:"—"},
  {w:10,d:"Mon",p:4,t:"Write: Communication Scorecard",tm:"30 min",tp:"writing",
   b:"Rate Week 1 vs. now:\n- Business context framing\n- Leadership narrative\n- Corporate vision articulation\n- Executive communication\n- Positive-first framing\n\nFor each: two scores (1–10) + one sentence of evidence.",
   up:"Completed scorecard.",rs:"—"},
  {w:10,d:"Tue",p:4,t:"Write: Final Materials Checklist",tm:"30–45 min",tp:"writing",
   b:"For every artifact, ask: \"Would Raisin's panel see a Director?\" and \"Am I leading with the positive?\"\n\nCheck all: FTU, P&S, Exp. Design, Portfolio, LinkedIn, a16z, Pitches, Q&A, Hard questions, Meta-narrative, Outreach.",
   up:"Checklist with status.",rs:"—"},
  {w:10,d:"Wed",p:4,t:"Reread: Director Reframe Guide",tm:"40–45 min",tp:"reading",
   b:"Reread the Director Reframe Guide after 9 weeks.\n\n1. What feels obvious now? What still challenges you? (5 min)\n2. Fix your weakest area from the scorecard. (15–20 min)",
   up:"Reflection + revisions.",rs:"Director Reframe Guide"},
  {w:10,d:"Thu",p:4,t:"Practice: Hardest Questions",tm:"45–60 min",tp:"practice",
   b:"All 5 hard questions from Week 8 plus:\n6. \"What makes you different from other Director candidates?\"\n7. \"How would you handle a CEO who doesn't value design?\"\n8. \"A time your team disagreed with your direction.\"\n\n90 seconds each. No pausing more than 5 seconds.",
   up:"Self-review — which still trip you up?",rs:"—"},
  {w:10,d:"Fri",p:4,t:"The Final Run",tm:"45–60 min",tp:"practice",
   b:"Full 45-minute mock interview.\n\nWatch Week 1 recording, then this one, back to back.\n\nWrite: What changed? What surprised you? How has your default framing shifted?",
   up:"Final self-assessment.",rs:"—"},
];
